micronaut:
  application:
    name: management

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/predator?ssl=false
    driverClassName: org.postgresql.Driver
    username: predator
    password: predator123

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true